import { ContractApiResponse } from "../api/useContractAPI";
import { OrderCardProps } from "../components/Order";
import { CardProps } from "../components/Result";

export const orderCardData: ContractApiResponse = {
    items: [
        {
            productImages: [
                "https://via.placeholder.com/600x400/ff7f7f/333333",
                "https://via.placeholder.com/600x400/ffbf7f/333333",
                "https://via.placeholder.com/600x400/ffff7f/333333",
            ],
            productName: "Dresses",
            productCode: "R23CD02",
            wholesalePrice: 150.00,
            suggestedRetail: 450.00,
        },
        {
            productImages: [
                "https://via.placeholder.com/600x400/7f7fff/333333",
                "https://via.placeholder.com/600x400/7fbfff/333333",
                "https://via.placeholder.com/600x400/7fffff/333333",
            ],
            productName: "Tops",
            productCode: "R23CT09",
            wholesalePrice: 65.00,
            suggestedRetail: 195.00,
        },
        {
            productImages: [
                "https://via.placeholder.com/600x400/7fff7f/333333",
                "https://via.placeholder.com/600x400/bfff7f/333333",
                "https://via.placeholder.com/600x400/ffff7f/333333",
            ],
            productName: "Skirts",
            productCode: "R23CS08",
            wholesalePrice: 65.00,
            suggestedRetail: 195.00,
        },
        {
            productImages: [
                "https://via.placeholder.com/600x400/ff7fff/333333",
                "https://via.placeholder.com/600x400/ff7f7f/333333",
                "https://via.placeholder.com/600x400/ffbf7f/333333",
            ],
            productName: "Dresses",
            productCode: "R23CD05",
            wholesalePrice: 140.00,
            suggestedRetail: 420.00,
        },
        {
            productImages: [
                "https://via.placeholder.com/600x400/ff7fff/333333",
                "https://via.placeholder.com/600x400/ff7f7f/333333",
                "https://via.placeholder.com/600x400/ffbf7f/333333",
            ],
            productName: "Dresses",
            productCode: "R23CD05",
            wholesalePrice: 140.00,
            suggestedRetail: 420.00,
        },
        {
            productImages: [
                "https://via.placeholder.com/600x400/ff7fff/333333",
                "https://via.placeholder.com/600x400/ff7f7f/333333",
                "https://via.placeholder.com/600x400/ffbf7f/333333",
            ],
            productName: "Dresses",
            productCode: "R23CD05",
            wholesalePrice: 140.00,
            suggestedRetail: 420.00,
        },
        {
            productImages: [
                "https://via.placeholder.com/600x400/ff7fff/333333",
                "https://via.placeholder.com/600x400/ff7f7f/333333",
                "https://via.placeholder.com/600x400/ffbf7f/333333",
            ],
            productName: "Dresses",
            productCode: "R23CD05",
            wholesalePrice: 140.00,
            suggestedRetail: 420.00,
        },
    ],
};

export const cardDataList: CardProps[] = [
    {
        img1URL: "https://via.placeholder.com/400x300?text=Acme+Fashion+1",
        img2URL: "https://via.placeholder.com/400x300?text=Acme+Fashion+2",
        name: 'Acme Fashion',
        location: 'New York, USA',
        revenue: '100M - 500M',
        price: '$50 - $500',
        category: 'Apparel',
        pageID: 'acme-fashion-ny',
    },
    {
        img1URL: "https://via.placeholder.com/400x300?text=Stylish+Designs+1",
        img2URL: "https://via.placeholder.com/400x300?text=Stylish+Designs+2",
        name: 'Stylish Designs',
        location: 'London, UK',
        revenue: '50M - 100M',
        price: '$30 - $300',
        category: 'Accessories',
        pageID: 'stylish-designs-london',
    },
    {
        img1URL: "https://via.placeholder.com/400x300?text=Trendy+Threads+1",
        img2URL: "https://via.placeholder.com/400x300?text=Trendy+Threads+2",
        name: 'Trendy Threads',
        location: 'Paris, France',
        revenue: '500M - 1B',
        price: '$80 - $800',
        category: 'Apparel',
        pageID: 'trendy-threads-paris',
    },
    {
        img1URL: "https://via.placeholder.com/400x300?text=Chic+Boutique+1",
        img2URL: "https://via.placeholder.com/400x300?text=Chic+Boutique+2",
        name: 'Chic Boutique',
        location: 'Milan, Italy',
        revenue: '20M - 50M',
        price: '$40 - $400',
        category: 'Accessories',
        pageID: 'chic-boutique-milan',
    },
    {
        img1URL: "https://via.placeholder.com/400x300?text=Elegant+Essentials+1",
        img2URL: "https://via.placeholder.com/400x300?text=Elegant+Essentials+2",
        name: 'Elegant Essentials',
        location: 'Tokyo, Japan',
        revenue: '100M - 500M',
        price: '$60 - $600',
        category: 'Apparel',
        pageID: 'elegant-essentials-tokyo-1',
    },
    {
        img1URL: "https://via.placeholder.com/400x300?text=Elegant+Essentials+1",
        img2URL: "https://via.placeholder.com/400x300?text=Elegant+Essentials+2",
        name: 'Elegant Essentials',
        location: 'Tokyo, Japan',
        revenue: '100M - 500M',
        price: '$60 - $600',
        category: 'Apparel',
        pageID: 'elegant-essentials-tokyo-2',
    },
    {
        img1URL: "https://via.placeholder.com/400x300?text=Elegant+Essentials+1",
        img2URL: "https://via.placeholder.com/400x300?text=Elegant+Essentials+2",
        name: 'Elegant Essentials',
        location: 'Tokyo, Japan',
        revenue: '100M - 500M',
        price: '$60 - $600',
        category: 'Apparel',
        pageID: 'elegant-essentials-tokyo-3',
    },
    {
        img1URL: "https://via.placeholder.com/400x300?text=Elegant+Essentials+1",
        img2URL: "https://via.placeholder.com/400x300?text=Elegant+Essentials+2",
        name: 'Elegant Essentials',
        location: 'Tokyo, Japan',
        revenue: '100M - 500M',
        price: '$60 - $600',
        category: 'Apparel',
        pageID: 'elegant-essentials-tokyo-4',
    },
    {
        img1URL: "https://via.placeholder.com/400x300?text=Elegant+Essentials+1",
        img2URL: "https://via.placeholder.com/400x300?text=Elegant+Essentials+2",
        name: 'Elegant Essentials',
        location: 'Tokyo, Japan',
        revenue: '100M - 500M',
        price: '$60 - $600',
        category: 'Apparel',
        pageID: 'elegant-essentials-tokyo-5',
    },
    {
        img1URL: "https://via.placeholder.com/400x300?text=Elegant+Essentials+1",
        img2URL: "https://via.placeholder.com/400x300?text=Elegant+Essentials+2",
        name: 'Elegant Essentials',
        location: 'Tokyo, Japan',
        revenue: '100M - 500M',
        price: '$60 - $600',
        category: 'Apparel',
        pageID: 'elegant-essentials-tokyo-6',
    },
];